# Generated by Django 5.2.5 on 2025-09-02 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('taches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaire',
            name='tache',
        ),
        migrations.AddField(
            model_name='commentaire',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
