# Generated by Django 5.2.5 on 2025-09-10 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammembers',
            old_name='date_ajout',
            new_name='date_joined',
        ),
        migrations.AlterUniqueTogether(
            name='teammembers',
            unique_together={('team', 'user')},
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammembers', to='taches.team'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teammembers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='role',
        ),
    ]
