# Generated by Django 5.2.5 on 2025-08-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='chef_equipe',
        ),
        migrations.AddField(
            model_name='teammembers',
            name='role',
            field=models.CharField(choices=[('chef', 'Chef d’équipe'), ('membre', 'Membre d’équipe')], default='membre', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
